#!/usr/bin/env bash
set -euo pipefail

# Simple SSH management helper for this repo.
# Places / uses keys in this folder (id_rsa, id_rsa.pub).
# Functions: gen-key, copy-to-container, copy-to-host, remove-key, status

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEY_PRIVATE="$SCRIPT_DIR/id_rsa"
KEY_PUBLIC="$SCRIPT_DIR/id_rsa.pub"

SSH_USER="${SSH_USER:-root}"
SSH_PORT="${SSH_PORT:-22}"
SSH_HOST="${SSH_HOST:-}"         # when copying to a remote host
CONTAINER_NAME="${CONTAINER_NAME:-}" # when copying into a docker container

usage(){
    cat <<EOF
Usage: $(basename "$0") <command>

Commands:
  gen-key             Generate an ed25519 keypair at $KEY_PRIVATE (if missing)
  copy-to-container   Copy public key into a running Docker container's authorized_keys
                      requires CONTAINER_NAME env or --container <name>
  copy-to-host        Use ssh-copy-id (or fallback) to install public key on remote host
                      requires SSH_HOST env or --host <host>
  remove-key          Remove the public key from host/container authorized_keys
  status              Show basic status of keys and optional settings
  help                Show this help

Environment variables (can be exported or passed inline):
  SSH_USER, SSH_PORT, SSH_HOST, CONTAINER_NAME

Examples:
  SSH_HOST=192.168.1.10 SSH_USER=ubuntu ./ssh_manage.sh copy-to-host
  CONTAINER_NAME=my_smo_container ./ssh_manage.sh copy-to-container
EOF
}

gen_key(){
    if [ -f "$KEY_PRIVATE" ] || [ -f "$KEY_PUBLIC" ]; then
        echo "Key pair already exists at $KEY_PRIVATE and $KEY_PUBLIC"
        return 0
    fi
    echo "Generating ed25519 key pair at: $KEY_PRIVATE"
    ssh-keygen -t ed25519 -f "$KEY_PRIVATE" -N "" -C "smo-autogenerated-$(date +%Y%m%d%H%M%S)"
    chmod 600 "$KEY_PRIVATE" || true
    chmod 644 "$KEY_PUBLIC" || true
    echo "Created keys. Public key path: $KEY_PUBLIC"
}

copy_to_container(){
    local container="${1:-$CONTAINER_NAME}"
    if [ -z "$container" ]; then
        echo "No container name provided. Set CONTAINER_NAME env or pass the name as first arg." >&2
        return 2
    fi
    if ! command -v docker >/dev/null 2>&1; then
        echo "docker not found in PATH. Cannot copy to container." >&2
        return 3
    fi
    if [ ! -f "$KEY_PUBLIC" ]; then
        echo "Public key $KEY_PUBLIC not found. Run gen-key first." >&2
        return 4
    fi

    # detect user home inside container; prefer target user's home if possible
    echo "Copying $KEY_PUBLIC to container '$container' for user $SSH_USER"
    # create .ssh and append key
    docker exec -i "$container" sh -c 'mkdir -p /root/.ssh && chmod 700 /root/.ssh' || true
    # If user is not root, try to create for that user
    if [ "$SSH_USER" != "root" ]; then
        docker exec -i "$container" sh -c "mkdir -p /home/$SSH_USER/.ssh && chown $SSH_USER:$SSH_USER /home/$SSH_USER/.ssh && chmod 700 /home/$SSH_USER/.ssh" || true
    fi
    # Append key to appropriate authorized_keys path
    if [ "$SSH_USER" = "root" ]; then
        docker exec -i "$container" sh -c 'cat >> /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys' < "$KEY_PUBLIC"
    else
        docker exec -i "$container" sh -c "cat >> /home/$SSH_USER/.ssh/authorized_keys && chmod 600 /home/$SSH_USER/.ssh/authorized_keys" < "$KEY_PUBLIC"
        docker exec -i "$container" sh -c "chown $SSH_USER:$SSH_USER /home/$SSH_USER/.ssh/authorized_keys" || true
    fi
    echo "Public key appended inside container. Verify by trying: ssh -i $KEY_PRIVATE -p <port> $SSH_USER@<host>"
}

copy_to_host(){
    local host="${1:-$SSH_HOST}"
    if [ -z "$host" ]; then
        echo "No SSH_HOST provided. Set SSH_HOST env or pass host as first arg." >&2
        return 2
    fi
    if [ ! -f "$KEY_PUBLIC" ]; then
        echo "Public key $KEY_PUBLIC not found. Run gen-key first." >&2
        return 3
    fi

    # prefer ssh-copy-id when available
    if command -v ssh-copy-id >/dev/null 2>&1; then
        echo "Using ssh-copy-id to install key to $host (user=$SSH_USER port=$SSH_PORT)"
        ssh-copy-id -i "$KEY_PUBLIC" -p "$SSH_PORT" "$SSH_USER@$host"
    else
        echo "ssh-copy-id not found; attempting manual install (requires password)"
        # create remote .ssh and append key via ssh
        ssh -p "$SSH_PORT" "$SSH_USER@$host" "mkdir -p ~/.ssh && chmod 700 ~/.ssh" < /dev/null
        scp -P "$SSH_PORT" "$KEY_PUBLIC" "$SSH_USER@$host:~/.ssh/_temp_pub"
        ssh -p "$SSH_PORT" "$SSH_USER@$host" "cat ~/.ssh/_temp_pub >> ~/.ssh/authorized_keys && rm ~/.ssh/_temp_pub && chmod 600 ~/.ssh/authorized_keys"
    fi
    echo "Copy complete. Try: ssh -i $KEY_PRIVATE -p $SSH_PORT $SSH_USER@$host"
}

remove_key(){
    local target="${1:-$SSH_HOST}"
    if [ -n "$CONTAINER_NAME" ]; then
        echo "Removing key from container $CONTAINER_NAME"
        if [ ! -f "$KEY_PUBLIC" ]; then
            echo "Public key not found at $KEY_PUBLIC" >&2
            return 2
        fi
        local publine
        publine=$(cat "$KEY_PUBLIC")
        if [ "$SSH_USER" = "root" ]; then
            docker exec -i "$CONTAINER_NAME" sh -c "grep -vF -- \"$publine\" /root/.ssh/authorized_keys > /root/.ssh/authorized_keys.tmp || true && mv /root/.ssh/authorized_keys.tmp /root/.ssh/authorized_keys" || true
        else
            docker exec -i "$CONTAINER_NAME" sh -c "grep -vF -- \"$publine\" /home/$SSH_USER/.ssh/authorized_keys > /home/$SSH_USER/.ssh/authorized_keys.tmp || true && mv /home/$SSH_USER/.ssh/authorized_keys.tmp /home/$SSH_USER/.ssh/authorized_keys" || true
        fi
        echo "Removal attempt complete."
        return 0
    fi

    if [ -z "$target" ]; then
        echo "No host or container specified to remove key from." >&2
        return 3
    fi
    if [ ! -f "$KEY_PUBLIC" ]; then
        echo "Public key $KEY_PUBLIC not found." >&2
        return 4
    fi
    local publine
    publine=$(cat "$KEY_PUBLIC")
    echo "Trying to remove key from $target (user=$SSH_USER port=$SSH_PORT)"
    ssh -p "$SSH_PORT" "$SSH_USER@$target" "set -e; mkdir -p ~/.ssh; touch ~/.ssh/authorized_keys; grep -vF -- \"$publine\" ~/.ssh/authorized_keys > ~/.ssh/authorized_keys.tmp || true; mv ~/.ssh/authorized_keys.tmp ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys"
    echo "Removal attempted on host $target"
}

status(){
    echo "Script dir: $SCRIPT_DIR"
    echo "Private key: $KEY_PRIVATE -> $( [ -f "$KEY_PRIVATE" ] && echo "exists" || echo "MISSING" )"
    echo "Public key:  $KEY_PUBLIC -> $( [ -f "$KEY_PUBLIC" ] && echo "exists" || echo "MISSING" )"
    echo "SSH_USER=$SSH_USER SSH_PORT=$SSH_PORT SSH_HOST=$SSH_HOST CONTAINER_NAME=$CONTAINER_NAME"
}

# parse args
cmd="${1:-help}"
case "$cmd" in
    gen-key|gen|generate)
        gen_key
        ;;
    copy-to-container|copy-to-container)
        copy_to_container "${2:-}"
        ;;
    copy-to-host|copy-to-host)
        copy_to_host "${2:-}"
        ;;
    remove-key|remove)
        remove_key "${2:-}"
        ;;
    status)
        status
        ;;
    help|-h|--help)
        usage
        ;;
    *)
        echo "Unknown command: $cmd" >&2
        usage
        exit 2
        ;;
esac
